version: 2.1

orbs:
  maven: circleci/maven@0.0.12

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run: 'mvn clean'
          #command: 
  test:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run: 'mvn test'
          #  command: 'test'

#workflows:
#  maven_test:
#    jobs:
#      - maven/test:
#          command: 'clean test'
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
